# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import common_pb2 as common__pb2
import customer_pb2 as customer__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in customer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CustomerDBStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckSession = channel.unary_unary(
                '/marketplace.CustomerDB/CheckSession',
                request_serializer=customer__pb2.CheckSessionRequest.SerializeToString,
                response_deserializer=customer__pb2.CheckSessionResponse.FromString,
                _registered_method=True)
        self.SellerCreateAccount = channel.unary_unary(
                '/marketplace.CustomerDB/SellerCreateAccount',
                request_serializer=customer__pb2.SellerCreateAccountRequest.SerializeToString,
                response_deserializer=customer__pb2.SellerCreateAccountResponse.FromString,
                _registered_method=True)
        self.SellerLogin = channel.unary_unary(
                '/marketplace.CustomerDB/SellerLogin',
                request_serializer=customer__pb2.LoginRequest.SerializeToString,
                response_deserializer=customer__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.SellerLogout = channel.unary_unary(
                '/marketplace.CustomerDB/SellerLogout',
                request_serializer=customer__pb2.LogoutRequest.SerializeToString,
                response_deserializer=common__pb2.BasicResponse.FromString,
                _registered_method=True)
        self.GetSellerIdBySession = channel.unary_unary(
                '/marketplace.CustomerDB/GetSellerIdBySession',
                request_serializer=customer__pb2.SessionRequest.SerializeToString,
                response_deserializer=customer__pb2.GetSellerIdResponse.FromString,
                _registered_method=True)
        self.GetSellerRatingBySession = channel.unary_unary(
                '/marketplace.CustomerDB/GetSellerRatingBySession',
                request_serializer=customer__pb2.SessionRequest.SerializeToString,
                response_deserializer=customer__pb2.GetSellerRatingResponse.FromString,
                _registered_method=True)
        self.GetSellerRatingBySellerId = channel.unary_unary(
                '/marketplace.CustomerDB/GetSellerRatingBySellerId',
                request_serializer=customer__pb2.GetSellerRatingBySellerIdRequest.SerializeToString,
                response_deserializer=customer__pb2.GetSellerRatingResponse.FromString,
                _registered_method=True)
        self.BuyerCreateAccount = channel.unary_unary(
                '/marketplace.CustomerDB/BuyerCreateAccount',
                request_serializer=customer__pb2.BuyerCreateAccountRequest.SerializeToString,
                response_deserializer=customer__pb2.BuyerCreateAccountResponse.FromString,
                _registered_method=True)
        self.BuyerLogin = channel.unary_unary(
                '/marketplace.CustomerDB/BuyerLogin',
                request_serializer=customer__pb2.LoginRequest.SerializeToString,
                response_deserializer=customer__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.BuyerLogout = channel.unary_unary(
                '/marketplace.CustomerDB/BuyerLogout',
                request_serializer=customer__pb2.LogoutRequest.SerializeToString,
                response_deserializer=common__pb2.BasicResponse.FromString,
                _registered_method=True)
        self.GetBuyerIdBySession = channel.unary_unary(
                '/marketplace.CustomerDB/GetBuyerIdBySession',
                request_serializer=customer__pb2.SessionRequest.SerializeToString,
                response_deserializer=customer__pb2.GetBuyerIdResponse.FromString,
                _registered_method=True)
        self.AddItemToCart = channel.unary_unary(
                '/marketplace.CustomerDB/AddItemToCart',
                request_serializer=customer__pb2.CartItemRequest.SerializeToString,
                response_deserializer=customer__pb2.CartResponse.FromString,
                _registered_method=True)
        self.RemoveItemFromCart = channel.unary_unary(
                '/marketplace.CustomerDB/RemoveItemFromCart',
                request_serializer=customer__pb2.CartItemRequest.SerializeToString,
                response_deserializer=customer__pb2.CartResponse.FromString,
                _registered_method=True)
        self.DisplayCart = channel.unary_unary(
                '/marketplace.CustomerDB/DisplayCart',
                request_serializer=customer__pb2.SessionRequest.SerializeToString,
                response_deserializer=customer__pb2.CartResponse.FromString,
                _registered_method=True)
        self.ClearCart = channel.unary_unary(
                '/marketplace.CustomerDB/ClearCart',
                request_serializer=customer__pb2.SessionRequest.SerializeToString,
                response_deserializer=common__pb2.BasicResponse.FromString,
                _registered_method=True)
        self.SaveCart = channel.unary_unary(
                '/marketplace.CustomerDB/SaveCart',
                request_serializer=customer__pb2.SessionRequest.SerializeToString,
                response_deserializer=customer__pb2.SaveCartResponse.FromString,
                _registered_method=True)
        self.GetBuyerPurchasesBySession = channel.unary_unary(
                '/marketplace.CustomerDB/GetBuyerPurchasesBySession',
                request_serializer=customer__pb2.SessionRequest.SerializeToString,
                response_deserializer=customer__pb2.PurchasesResponse.FromString,
                _registered_method=True)
        self.MakePurchase = channel.unary_unary(
                '/marketplace.CustomerDB/MakePurchase',
                request_serializer=customer__pb2.SessionRequest.SerializeToString,
                response_deserializer=common__pb2.BasicResponse.FromString,
                _registered_method=True)


class CustomerDBServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckSession(self, request, context):
        """sessions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SellerCreateAccount(self, request, context):
        """seller
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SellerLogin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SellerLogout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSellerIdBySession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSellerRatingBySession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSellerRatingBySellerId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuyerCreateAccount(self, request, context):
        """buyer
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuyerLogin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuyerLogout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBuyerIdBySession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddItemToCart(self, request, context):
        """cart (buyer)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveItemFromCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisplayCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBuyerPurchasesBySession(self, request, context):
        """purchases (buyer)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MakePurchase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CustomerDBServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckSession,
                    request_deserializer=customer__pb2.CheckSessionRequest.FromString,
                    response_serializer=customer__pb2.CheckSessionResponse.SerializeToString,
            ),
            'SellerCreateAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.SellerCreateAccount,
                    request_deserializer=customer__pb2.SellerCreateAccountRequest.FromString,
                    response_serializer=customer__pb2.SellerCreateAccountResponse.SerializeToString,
            ),
            'SellerLogin': grpc.unary_unary_rpc_method_handler(
                    servicer.SellerLogin,
                    request_deserializer=customer__pb2.LoginRequest.FromString,
                    response_serializer=customer__pb2.LoginResponse.SerializeToString,
            ),
            'SellerLogout': grpc.unary_unary_rpc_method_handler(
                    servicer.SellerLogout,
                    request_deserializer=customer__pb2.LogoutRequest.FromString,
                    response_serializer=common__pb2.BasicResponse.SerializeToString,
            ),
            'GetSellerIdBySession': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSellerIdBySession,
                    request_deserializer=customer__pb2.SessionRequest.FromString,
                    response_serializer=customer__pb2.GetSellerIdResponse.SerializeToString,
            ),
            'GetSellerRatingBySession': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSellerRatingBySession,
                    request_deserializer=customer__pb2.SessionRequest.FromString,
                    response_serializer=customer__pb2.GetSellerRatingResponse.SerializeToString,
            ),
            'GetSellerRatingBySellerId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSellerRatingBySellerId,
                    request_deserializer=customer__pb2.GetSellerRatingBySellerIdRequest.FromString,
                    response_serializer=customer__pb2.GetSellerRatingResponse.SerializeToString,
            ),
            'BuyerCreateAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.BuyerCreateAccount,
                    request_deserializer=customer__pb2.BuyerCreateAccountRequest.FromString,
                    response_serializer=customer__pb2.BuyerCreateAccountResponse.SerializeToString,
            ),
            'BuyerLogin': grpc.unary_unary_rpc_method_handler(
                    servicer.BuyerLogin,
                    request_deserializer=customer__pb2.LoginRequest.FromString,
                    response_serializer=customer__pb2.LoginResponse.SerializeToString,
            ),
            'BuyerLogout': grpc.unary_unary_rpc_method_handler(
                    servicer.BuyerLogout,
                    request_deserializer=customer__pb2.LogoutRequest.FromString,
                    response_serializer=common__pb2.BasicResponse.SerializeToString,
            ),
            'GetBuyerIdBySession': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBuyerIdBySession,
                    request_deserializer=customer__pb2.SessionRequest.FromString,
                    response_serializer=customer__pb2.GetBuyerIdResponse.SerializeToString,
            ),
            'AddItemToCart': grpc.unary_unary_rpc_method_handler(
                    servicer.AddItemToCart,
                    request_deserializer=customer__pb2.CartItemRequest.FromString,
                    response_serializer=customer__pb2.CartResponse.SerializeToString,
            ),
            'RemoveItemFromCart': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveItemFromCart,
                    request_deserializer=customer__pb2.CartItemRequest.FromString,
                    response_serializer=customer__pb2.CartResponse.SerializeToString,
            ),
            'DisplayCart': grpc.unary_unary_rpc_method_handler(
                    servicer.DisplayCart,
                    request_deserializer=customer__pb2.SessionRequest.FromString,
                    response_serializer=customer__pb2.CartResponse.SerializeToString,
            ),
            'ClearCart': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearCart,
                    request_deserializer=customer__pb2.SessionRequest.FromString,
                    response_serializer=common__pb2.BasicResponse.SerializeToString,
            ),
            'SaveCart': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveCart,
                    request_deserializer=customer__pb2.SessionRequest.FromString,
                    response_serializer=customer__pb2.SaveCartResponse.SerializeToString,
            ),
            'GetBuyerPurchasesBySession': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBuyerPurchasesBySession,
                    request_deserializer=customer__pb2.SessionRequest.FromString,
                    response_serializer=customer__pb2.PurchasesResponse.SerializeToString,
            ),
            'MakePurchase': grpc.unary_unary_rpc_method_handler(
                    servicer.MakePurchase,
                    request_deserializer=customer__pb2.SessionRequest.FromString,
                    response_serializer=common__pb2.BasicResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'marketplace.CustomerDB', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('marketplace.CustomerDB', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CustomerDB(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.CustomerDB/CheckSession',
            customer__pb2.CheckSessionRequest.SerializeToString,
            customer__pb2.CheckSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SellerCreateAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.CustomerDB/SellerCreateAccount',
            customer__pb2.SellerCreateAccountRequest.SerializeToString,
            customer__pb2.SellerCreateAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SellerLogin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.CustomerDB/SellerLogin',
            customer__pb2.LoginRequest.SerializeToString,
            customer__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SellerLogout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.CustomerDB/SellerLogout',
            customer__pb2.LogoutRequest.SerializeToString,
            common__pb2.BasicResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSellerIdBySession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.CustomerDB/GetSellerIdBySession',
            customer__pb2.SessionRequest.SerializeToString,
            customer__pb2.GetSellerIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSellerRatingBySession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.CustomerDB/GetSellerRatingBySession',
            customer__pb2.SessionRequest.SerializeToString,
            customer__pb2.GetSellerRatingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSellerRatingBySellerId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.CustomerDB/GetSellerRatingBySellerId',
            customer__pb2.GetSellerRatingBySellerIdRequest.SerializeToString,
            customer__pb2.GetSellerRatingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BuyerCreateAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.CustomerDB/BuyerCreateAccount',
            customer__pb2.BuyerCreateAccountRequest.SerializeToString,
            customer__pb2.BuyerCreateAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BuyerLogin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.CustomerDB/BuyerLogin',
            customer__pb2.LoginRequest.SerializeToString,
            customer__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BuyerLogout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.CustomerDB/BuyerLogout',
            customer__pb2.LogoutRequest.SerializeToString,
            common__pb2.BasicResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBuyerIdBySession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.CustomerDB/GetBuyerIdBySession',
            customer__pb2.SessionRequest.SerializeToString,
            customer__pb2.GetBuyerIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddItemToCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.CustomerDB/AddItemToCart',
            customer__pb2.CartItemRequest.SerializeToString,
            customer__pb2.CartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveItemFromCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.CustomerDB/RemoveItemFromCart',
            customer__pb2.CartItemRequest.SerializeToString,
            customer__pb2.CartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisplayCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.CustomerDB/DisplayCart',
            customer__pb2.SessionRequest.SerializeToString,
            customer__pb2.CartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.CustomerDB/ClearCart',
            customer__pb2.SessionRequest.SerializeToString,
            common__pb2.BasicResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.CustomerDB/SaveCart',
            customer__pb2.SessionRequest.SerializeToString,
            customer__pb2.SaveCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBuyerPurchasesBySession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.CustomerDB/GetBuyerPurchasesBySession',
            customer__pb2.SessionRequest.SerializeToString,
            customer__pb2.PurchasesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MakePurchase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.CustomerDB/MakePurchase',
            customer__pb2.SessionRequest.SerializeToString,
            common__pb2.BasicResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
