# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import common_pb2 as common__pb2
import product_pb2 as product__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in product_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProductDBStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterItemForSale = channel.unary_unary(
                '/marketplace.ProductDB/RegisterItemForSale',
                request_serializer=product__pb2.RegisterItemForSaleRequest.SerializeToString,
                response_deserializer=product__pb2.RegisterItemForSaleResponse.FromString,
                _registered_method=True)
        self.ChangeItemPrice = channel.unary_unary(
                '/marketplace.ProductDB/ChangeItemPrice',
                request_serializer=product__pb2.ChangeItemPriceRequest.SerializeToString,
                response_deserializer=common__pb2.BasicResponse.FromString,
                _registered_method=True)
        self.UpdateUnitsForSale = channel.unary_unary(
                '/marketplace.ProductDB/UpdateUnitsForSale',
                request_serializer=product__pb2.UpdateUnitsForSaleRequest.SerializeToString,
                response_deserializer=product__pb2.UpdateUnitsForSaleResponse.FromString,
                _registered_method=True)
        self.DisplayItemsForSale = channel.unary_unary(
                '/marketplace.ProductDB/DisplayItemsForSale',
                request_serializer=product__pb2.DisplayItemsForSaleRequest.SerializeToString,
                response_deserializer=product__pb2.ItemsResponse.FromString,
                _registered_method=True)
        self.SearchItemsForSale = channel.unary_unary(
                '/marketplace.ProductDB/SearchItemsForSale',
                request_serializer=product__pb2.SearchItemsForSaleRequest.SerializeToString,
                response_deserializer=product__pb2.ItemsResponse.FromString,
                _registered_method=True)
        self.GetItem = channel.unary_unary(
                '/marketplace.ProductDB/GetItem',
                request_serializer=product__pb2.GetItemRequest.SerializeToString,
                response_deserializer=product__pb2.GetItemResponse.FromString,
                _registered_method=True)
        self.ProvideFeedback = channel.unary_unary(
                '/marketplace.ProductDB/ProvideFeedback',
                request_serializer=product__pb2.ProvideFeedbackRequest.SerializeToString,
                response_deserializer=product__pb2.ProvideFeedbackResponse.FromString,
                _registered_method=True)
        self.DeductStock = channel.unary_unary(
                '/marketplace.ProductDB/DeductStock',
                request_serializer=product__pb2.DeductStockRequest.SerializeToString,
                response_deserializer=common__pb2.BasicResponse.FromString,
                _registered_method=True)


class ProductDBServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterItemForSale(self, request, context):
        """Seller APIs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangeItemPrice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUnitsForSale(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisplayItemsForSale(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchItemsForSale(self, request, context):
        """Buyer APIs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProvideFeedback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeductStock(self, request, context):
        """NEW: Used by CustomerDB.MakePurchase to atomically deduct stock
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductDBServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterItemForSale': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterItemForSale,
                    request_deserializer=product__pb2.RegisterItemForSaleRequest.FromString,
                    response_serializer=product__pb2.RegisterItemForSaleResponse.SerializeToString,
            ),
            'ChangeItemPrice': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangeItemPrice,
                    request_deserializer=product__pb2.ChangeItemPriceRequest.FromString,
                    response_serializer=common__pb2.BasicResponse.SerializeToString,
            ),
            'UpdateUnitsForSale': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUnitsForSale,
                    request_deserializer=product__pb2.UpdateUnitsForSaleRequest.FromString,
                    response_serializer=product__pb2.UpdateUnitsForSaleResponse.SerializeToString,
            ),
            'DisplayItemsForSale': grpc.unary_unary_rpc_method_handler(
                    servicer.DisplayItemsForSale,
                    request_deserializer=product__pb2.DisplayItemsForSaleRequest.FromString,
                    response_serializer=product__pb2.ItemsResponse.SerializeToString,
            ),
            'SearchItemsForSale': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchItemsForSale,
                    request_deserializer=product__pb2.SearchItemsForSaleRequest.FromString,
                    response_serializer=product__pb2.ItemsResponse.SerializeToString,
            ),
            'GetItem': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItem,
                    request_deserializer=product__pb2.GetItemRequest.FromString,
                    response_serializer=product__pb2.GetItemResponse.SerializeToString,
            ),
            'ProvideFeedback': grpc.unary_unary_rpc_method_handler(
                    servicer.ProvideFeedback,
                    request_deserializer=product__pb2.ProvideFeedbackRequest.FromString,
                    response_serializer=product__pb2.ProvideFeedbackResponse.SerializeToString,
            ),
            'DeductStock': grpc.unary_unary_rpc_method_handler(
                    servicer.DeductStock,
                    request_deserializer=product__pb2.DeductStockRequest.FromString,
                    response_serializer=common__pb2.BasicResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'marketplace.ProductDB', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('marketplace.ProductDB', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProductDB(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterItemForSale(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.ProductDB/RegisterItemForSale',
            product__pb2.RegisterItemForSaleRequest.SerializeToString,
            product__pb2.RegisterItemForSaleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChangeItemPrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.ProductDB/ChangeItemPrice',
            product__pb2.ChangeItemPriceRequest.SerializeToString,
            common__pb2.BasicResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUnitsForSale(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.ProductDB/UpdateUnitsForSale',
            product__pb2.UpdateUnitsForSaleRequest.SerializeToString,
            product__pb2.UpdateUnitsForSaleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisplayItemsForSale(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.ProductDB/DisplayItemsForSale',
            product__pb2.DisplayItemsForSaleRequest.SerializeToString,
            product__pb2.ItemsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchItemsForSale(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.ProductDB/SearchItemsForSale',
            product__pb2.SearchItemsForSaleRequest.SerializeToString,
            product__pb2.ItemsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.ProductDB/GetItem',
            product__pb2.GetItemRequest.SerializeToString,
            product__pb2.GetItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProvideFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.ProductDB/ProvideFeedback',
            product__pb2.ProvideFeedbackRequest.SerializeToString,
            product__pb2.ProvideFeedbackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeductStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.ProductDB/DeductStock',
            product__pb2.DeductStockRequest.SerializeToString,
            common__pb2.BasicResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
